### ISSUE TITLE
Default token_payload doesn't return a random hex value

### ISSUE THREAD

**Issue by nbibler** [doorkeeper-gem/doorkeeper-jwt#32]
The README indicates that if the `token_payload` is left unset, then it:

> Defaults to a randomly generated token in a hash: { token: "RANDOM-TOKEN" }

However, that is not this library's current behavior.

The following is what is actually generated if you fail to set a `token_payload`:

```
{
  "token": "#<Method: SecureRandom.hex>"
}
```

The token payload's default value does not appear to be getting called (the `hex` method reference is simply being converted to a string) and no random hash is generated:

https://github.com/doorkeeper-gem/doorkeeper-jwt/blob/25223d6c3b585e45202d37ea90a68dc527b4502f/lib/doorkeeper/jwt/config.rb#L112-L115

**Comment by ransombriggs** [comment]
I can confirm this, I started with an empty config and noticed this as well when testing.

**Comment by ransombriggs** [comment]
I pushed up a fix for this issue: https://github.com/doorkeeper-gem/doorkeeper-jwt/pull/56
